# Generated by Django 6.0.4 on 2026-04-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('total_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(max_length=4)),
                ('expiration_date', models.CharField(max_length=7)),
                ('estado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
